# Generated by Django 5.1.7 on 2025-05-20 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_server_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='server',
            new_name='server_id',
        ),
        migrations.RenameField(
            model_name='networktraffic',
            old_name='server',
            new_name='server_id',
        ),
        migrations.RenameField(
            model_name='resourceusage',
            old_name='server',
            new_name='server_id',
        ),
    ]
